# PostgreSQL. Versions 9.1 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ...
  password: ...
  host: localhost

development:
  <<: *default
  database: ...
test:
  <<: *default
  database: ...

production:
  <<: *default
  database: ...
  username: ...
  password: <%= ENV['FLASHCARDS_DATABASE_PASSWORD'] %>
